### PR TITLE
First draft of tool selection chapter

### LINKED ISSUE #7: Add a chapter on considerations for selecting communication tools
This seems like a natural fit for the guide: a chapter on communication habits and practices typical of successful open communities and organizations. How does working in a distributed fashion require people to think differently about their communication styles and preferences?

### PR DESCRIPTION
**Pull request by funnelfiasco**
Here it is for your review

### CODE REVIEW

**Comment by funnelfiasco** [comment]
Also: I intentionally left out anything about etiquette and practice because those are/will be covered in Jimmy's "Communication practices typical of high-performing remote teams" chapter and Joe's chapter (#16).

**Comment by semioticrobotic** [comment]
Can't wait to review. Thanks, @funnelfiasco, for your awesome work.

**Comment by semioticrobotic** [comment]
Ah! Forgot to leave a comment here. Sorry, @funnelfiasco! I'm finished with the first round of edits and happy to discuss. Thanks for this great chapter.

**Comment by semioticrobotic** [comment]
Hey @trncb: Would you mind giving this a second look?

As you can see (above), this is @funnelfiasco's first draft and I've made some edits and suggestions on it, but a more thorough cleanup may be helpful as @funnelfiasco puts his finishing touches in.

**Comment by trncb** [comment]
@funnelfiasco great article!

I have made a few more suggestions for consideration.

**Comment by semioticrobotic** [comment]
This is great, @trncb. Thanks so much for catching all these mistakes that slipped by us.

The only changes on which I'd push back are those related to the use of em dashes (—). You've proposed changing those to hyphens, which isn't really our style (em dashes without spaces is our style for offsetting clauses for emphasis, and it renders most appropriately in print and typeset).

**Comment by funnelfiasco** [comment]
@trncb you capitalized "Internet". I love you already. :-) I'm with @semioticrobotic on the em dashes though&mdash;copious em dashery is part of my #Personal #Brand.

@semioticrobotic I read through the chapter as-is and I couldn't tell where my draft ended and your edits begin. I also _did_ add the consideration that I wasn't sure if I had but was definitely going to if I hadn't, so from my perspective this is ready once the em dashes are restored. :wink:

**Comment by trncb** [comment]
haha, thanks @funnelfiasco.

No problem with regards to the em dash, I'll fix that right up.

**Comment by semioticrobotic** [comment]
> @semioticrobotic I read through the chapter as-is and I couldn't tell where my draft ended and your edits begin. I also _did_ add the consideration that I wasn't sure if I had but was definitely going to if I hadn't, so from my perspective this is ready once the em dashes are restored.

No greater compliment for an editor. Thanks, @funnelfiasco. Glad it's to your liking. When @trncb makes his final tweaks, we'll get it moving along. Huge **thank you** for contributing this great resource.

**Comment by trncb** [comment]
@funnelfiasco @semioticrobotic em dashes restored.

**Comment by semioticrobotic** [comment]
Thanks, all! Let's wrap this one.

**Pull request merged**
